name: Playwright CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:

    strategy:
      matrix:
        browser: [chromium, firefox]

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Azure Login
        if: github.ref == 'refs/heads/main'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure Playwright Tests
        if: github.ref == 'refs/heads/main'
        env:
          CI: true
          BROWSER: ${{ matrix.browser }}
          RETRIES: 2
          PARALLEL_THREAD: 2
          BASE_URL: https://rahulshettyacademy.com/client/#/auth/login
          REST_API_BASE_URL: https://rahulshettyacademy.com/client
          Timeout: 30000
          PLAYWRIGHT_SERVICE_URL: ${{ vars.PLAYWRIGHT_SERVICE_URL }}

        run: npx playwright test --config=playwright.service.config.ts --workers=2

      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-${{ matrix.browser }}
          path: allure-report/

      - name: Upload Allure Report to Azure Blob
        if: always()
        run: |
          az storage blob upload-batch \
            --account-name pwrrdaaf6 \
            --destination reports \
            --source allure-report \
            --auth-mode login